### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by balysv** [balysv/material-ripple#1]
Feature backlog:
- [x] Implement a callback  or post `onClick()` when Ripple animation ends so one can start heavy UI operations after. For example `ListView` item click and a transition to another screen.
- [x] Persistent Ripple effect flag (does not fade out and remains coloured)
- [x] Fix `AdapterView onItemClickListener` when `MaterialRippleLayout` is a item container
- [x] `rippleFade` attributes to control duration and strength of fade out effect
